version: '3.8'

services:
  webhook_server:
    build:
      context: .
    container_name: twitch_clips_downloader
    ports:
      - "5405:5405"
    volumes:
      - ./clips_downloader:/app
    restart: unless-stopped
    networks:
      - npm_npm
    env_file:
      - .env
    command: ["python3", "/app/webhook_server.py"]

  nginx:
    image: nginx:alpine
    container_name: twitch_clips_nginx
    ports:
      - "5404:5404"
    volumes:
      - ./clips_downloader:/app
      - ./nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/404.html:/app/404.html # for custom 404 page
    restart: unless-stopped
    networks:
      - npm_npm

networks:
  npm_npm:
    external: true
