services:
  webhook_server:
    build:
      context: .
    container_name: twitch_clips_downloader
    ports:
      - "5405:5405"  # No longer conflicting with nginx
    volumes:
         - ./app:/app
         - ./public/downloaded_clips:/public/downloaded_clips
    restart: unless-stopped
    env_file:
      - .env
    command: ["python3", "/app/webhook_server.py"]

  nginx:
    image: nginx:alpine
    container_name: twitch_clips_nginx
    ports:
      - "5404:5404"  # Nginx will serve the HTML/MP4s on this port
    volumes:
        - ./public:/usr/share/nginx/html
        - ./nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/404.html:/usr/share/nginx/html/404.html  # ← fixed
    restart: unless-stopped
