server {
    listen 5404 default_server;
    root /usr/share/nginx/html;
    index generated_index.html;

    location = / {
        try_files $uri $uri/ /generated_index.html =404;
    }

    location = /clips.json {
        try_files /clips.json =404;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}

# When you want to use a custom 404 page and index file for showing all clips
# 
#server {
#    listen 5404 default_server;
#    root /usr/share/nginx/html;
#    index generated_index.html;

#    location = / {
#        try_files $uri $uri/ /generated_index.html =404;
#    }

#    location = /clips.json {
#        try_files /clips.json =404;
#        add_header Access-Control-Allow-Origin *;
#        add_header Cache-Control "no-cache, no-store, must-revalidate";
#    }

#    location /favicon_io/ {
#        try_files $uri =404;
#    }

#    location / {
#        try_files $uri $uri/ =404;
#    }

#    error_page 404 /404.html;
#    location = /404.html {
#        root /usr/share/nginx/html;
#        internal;
#    }
#}